name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build (prod) with dynamic base path
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          npm run build -- --configuration production --base-href "/$REPO_NAME/" --deploy-url "/$REPO_NAME/"

      - name: SPA fallback (copy index.html to 404.html)
        id: spa
        run: |
          set -e
          DIST_BASE="dist/http-client"
          INDEX_FILE=""
          if [ -f "$DIST_BASE/browser/index.html" ]; then
            INDEX_FILE="$DIST_BASE/browser/index.html"
          elif [ -f "$DIST_BASE/index.html" ]; then
            INDEX_FILE="$DIST_BASE/index.html"
          else
            INDEX_FILE=$(find "$DIST_BASE" -maxdepth 4 -name "index.html" | head -n 1 || true)
          fi

          if [ -z "$INDEX_FILE" ]; then
            echo "No index.html found under $DIST_BASE" >&2
            echo "Tree of $DIST_BASE:"
            ls -R "$DIST_BASE" || true
            exit 1
          fi

          DIST_DIR="$(dirname "$INDEX_FILE")"
          cp -f "$INDEX_FILE" "$DIST_DIR/404.html"
          echo "dist_dir=$DIST_DIR" >> $GITHUB_OUTPUT

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.spa.outputs.dist_dir }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4